---
title: "2024-sludge"
output: html_notebook
---

## Projects
***

#### PFAS contamination and biosolid spread map
*Summary from Sara*

>
I would like to see if we can create a map that overlaps risk of PFAS contamination (known and suspected PFAS contamination sites) with locations that spread biosolids (aka municipal wastewater treatment plants). If we knew where there is high PFAS risk AND the city spreads biosolids, this would be very interesting. I’m interested in national data but we could start with one state just to see how it looks.
>
> Maps that display known and suspected PFAS contamination sites:
Example 1: Environmental Working Group
Interactive Map: PFAS Contamination Crisis: New Data Show 5,021 Sites in 50 States
Example 2: PFAS Working Group
https://experience.arcgis.com/experience/12412ab41b3141598e0bb48523a7c940/
>
Source of municipal wastewater treatment plants that spread biosolids: EPA’s ECHO database. 
Background: https://echo.epa.gov/help/reports/biosolids-facility-report-help
https://echo.epa.gov/help/facility-search/biosolids-search-results-help
>
Go to https://echo.epa.gov/facilities/facility-search and under “Media Program” select “biosolids.” You should get more than 4,000 facilities nationwide. I am not positive all states are represented here. For Missouri, it should return 418 facilities. 
NOTE: If you search “biosolids annual report” that is a smaller subset of large WWTPs, which is about 100 in Missouri. I figure try the larger data set first.


***



Mapping the location of fields on which industrial sludge will be spread, as identified in permits with the Missouri Department of Natural Resources. These locations are id’d with UTM coordinates. Here are two permits to start with, but we should have more from a records request soon.
HydroAg permit application: https://dnr.mo.gov/document/draft-missouri-state-operating-permit-mo0140490-feb-16-2024
Synagro permit application: https://dnr.mo.gov/document/draft-missouri-state-operating-permit-mo0140244-feb-16-2024 
